version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    reviewers:
      - aaronspruit

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    reviewers:
      - aaronspruit

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: deps
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff"
          - "coverage"
        update-types:
          - minor
          - patch
    reviewers:
      - aaronspruit
